/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHILE = 6;
  /** RegularExpression Id. */
  int LOOP = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int ELSIF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int EXIT = 13;
  /** RegularExpression Id. */
  int GET = 14;
  /** RegularExpression Id. */
  int PUT = 15;
  /** RegularExpression Id. */
  int SQRT = 16;
  /** RegularExpression Id. */
  int ABS = 17;
  /** RegularExpression Id. */
  int Id = 18;
  /** RegularExpression Id. */
  int Int = 19;
  /** RegularExpression Id. */
  int String = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<WHILE>",
    "<LOOP>",
    "<IF>",
    "<THEN>",
    "<ELSIF>",
    "<ELSE>",
    "<END>",
    "<EXIT>",
    "<GET>",
    "<PUT>",
    "<SQRT>",
    "<ABS>",
    "<Id>",
    "<Int>",
    "<String>",
    "\":\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"|\"",
    "\"&\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"/=\"",
    "\">=\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
  };

}
